# Generated by Django 4.1.2 on 2022-11-07 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pontosColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('pix', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('horaAbertura', models.TimeField(default='00:00')),
                ('horaFechamento', models.TimeField(default='00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('doador', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pontocoleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pontoscoleta')),
            ],
        ),
    ]
