# Generated by Django 4.1.2 on 2022-10-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioDoador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pontoscoleta',
            name='telefone',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuariodoador')),
                ('pontocoleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pontoscoleta')),
            ],
        ),
    ]
