# Generated by Django 4.1.2 on 2022-10-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuariodoador_pontoscoleta_telefone_doacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoscoleta',
            name='horaAbertura',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='pontoscoleta',
            name='horaFechamento',
            field=models.TimeField(default='00:00'),
        ),
    ]
