# Generated by Django 4.1.2 on 2022-10-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_pontoscoleta_horaabertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoscoleta',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
