# Generated by Django 4.1.2 on 2022-10-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_pontoscoleta_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodoador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
